# Generated by Django 5.2.1 on 2025-05-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_alter_courseresearch_unique_together_and_more"),
        ("professors", "0001_initial"),
        ("research_groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseResearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "research_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research_groups.researchgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course research",
                "verbose_name_plural": "Course researches",
                "unique_together": {("course", "research_group")},
            },
        ),
        migrations.CreateModel(
            name="ProfessorCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.professor",
                    ),
                ),
            ],
            options={
                "unique_together": {("professor", "course")},
            },
        ),
    ]
