# Generated by Django 4.2.7 on 2025-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phdstudent',
            name='email',
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='research_topic',
            field=models.CharField(default='asdasd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='title',
            field=models.CharField(default='asdasd', max_length=10),
            preserve_default=False,
        ),
    ]
