# Generated by Django 5.2.1 on 2025-05-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('research_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField()),
                ('image_url', models.URLField(blank=True)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_students', to='research_groups.researchgroup')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_students', to='professors.professor')),
            ],
            options={
                'verbose_name': 'PhD student',
                'verbose_name_plural': 'PhD students',
            },
        ),
    ]
