# Generated by Django 4.2.7 on 2025-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='professor',
            name='title',
            field=models.CharField(default='web basic', max_length=20),
            preserve_default=False,
        ),
    ]
