# Generated by Django 5.2.1 on 2025-05-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('research_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('credits', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_groups.researchgroup')),
            ],
            options={
                'verbose_name': 'Course research',
                'verbose_name_plural': 'Course researches',
                'unique_together': {('course', 'research_group')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='research_groups',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseResearch', to='research_groups.researchgroup'),
        ),
        migrations.CreateModel(
            name='ProfessorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor')),
            ],
            options={
                'unique_together': {('professor', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='courses', through='courses.ProfessorCourse', to='professors.professor'),
        ),
    ]
