# Generated by Django 4.2.7 on 2025-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='No description yet'),
        ),
        migrations.AddField(
            model_name='course',
            name='format',
            field=models.CharField(default='Self-paced', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='web basic', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default='2025-10-25'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
