# Generated by Django 5.2.1 on 2025-05-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courseresearch",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="courseresearch",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseresearch",
            name="research_group",
        ),
        migrations.AlterUniqueTogether(
            name="professorcourse",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="professorcourse",
            name="course",
        ),
        migrations.RemoveField(
            model_name="professorcourse",
            name="professor",
        ),
    ]
