# Generated by Django 5.2.1 on 2025-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_courseresearch_unique_together_and_more"),
        ("professors", "0001_initial"),
        ("relations", "0001_initial"),
        ("research_groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="professors",
            field=models.ManyToManyField(
                related_name="courses",
                through="relations.ProfessorCourse",
                to="professors.professor",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="research_groups",
            field=models.ManyToManyField(
                related_name="courses",
                through="relations.CourseResearch",
                to="research_groups.researchgroup",
            ),
        ),
        migrations.DeleteModel(
            name="CourseResearch",
        ),
        migrations.DeleteModel(
            name="ProfessorCourse",
        ),
    ]
