# Generated by Django 5.2.1 on 2025-05-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_alter_course_professors_alter_course_research_groups_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="format",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
