# Generated by Django 5.2.1 on 2025-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_instructor_course_professor_and_more'),
        ('courses', '0004_alter_course_code_alter_course_credits_and_more'),
    ]

    operations = [
    ]
